### ISSUE TITLE
Create a setField method to set a single field

### ISSUE THREAD

**Issue by pabloelcolombiano** [vierge-noire/cakephp-fixture-factories#114]
The first argument should be the key, the second the value.

This should be RC with the actual implementation

**Comment by pabloelcolombiano** [comment]
We might need for RC to simply create an additional `setField()` method.

**Comment by pakacuda** [comment]
You mean it is more convenient than patchdData when setting one **single** field? Or do you see other use cases when this is also more convenient?

**Comment by pabloelcolombiano** [comment]
Yes, more convenient when setting one single field. It is simply easier to type, and occurs often.

**Comment by pakacuda** [comment]
Then fine with me for adding it
