### ISSUE TITLE
load the plugin only on dev mode

### ISSUE THREAD

**Issue by rrd108** [vierge-noire/cakephp-fixture-factories#148]
If you run composer with the no-dev switch on your production server like

`composer install --no-dev --no-interaction --optimize-autoloader`

You will run into this error:

```
Exception: Plugin CakephpFixtureFactories could not be found.
In [/xx/vendor/cakephp/cakephp/src/Core/PluginCollection.php, line 143]
```

This is because the plugin is installed as dev requirement. So in your `Application.php` file you should load accordingly, for example like this.

```php
protected function bootstrapCli(): void
{
    // some code here
    if (Configure::read('debug')) {
        $this->addPlugin('CakephpFixtureFactories');
    }
}
```

Maybe this is obvious for others, but I did not understand at the first glance why my deploy script fails.

So maybe it can be mentioned in the docs.

**Comment by pabloelcolombiano** [comment]
Yes, good point! I'll amend the docs.

**Comment by pabloelcolombiano** [comment]
Done.
