### ISSUE TITLE
Factory for association of a loaded plugin

### ISSUE THREAD

**Issue by gringlas** [vierge-noire/cakephp-fixture-factories#150]
As kind of a follow up to my question earlier: https://github.com/vierge-noire/cakephp-test-migrator/issues/27 
I was able to get the migrator to create the tables from the Tags plugin. 
Now I would like to create some of my entities with a FixtureFactory and add some associated Tags to them, like: 

```php
$tag = TagFactory::make([
            'slug' => 'death_star',
            'label' => 'Death Star'
        ])->persist();
$lesson = LessonFactory::make([
            'label' => 'How to destroy the Death Star'
       l])->with('Tags', $tag);
```

I'm not quite sure how to create a FixtureFactory for Tags, as those are part of the Tags plugin. When I use
`bin/cake bake fixture_factory Tags -p Tags` it will create a Factory into the vendors path of the plugin.
When I try to bake it it with `bin/cake bake fixture_factory Tags` I get the error  `Table 'myapp.tags' doesn't exist`, which is correct as the table actually is `myapp.tags_tags`.
When I try to bake it with `bin/cake bake fixtureFactory TagsTags` it will create a TagFactory, but I'm not able to insert data, like I try in above example I will recieve an exception from the FactoryAwareTrait in line [42](https://github.com/vierge-noire/cakephp-fixture-factories/blob/14e8a5d9edceb2ec2d2f201f50e5f01d13f20ee0/src/Factory/FactoryAwareTrait.php?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L42) as it tries to load from `Tags\Test\Factory\TagFactory`, which would be the vendor folder.

I'm using cake3.10 here, but I don't think that this is specific to cake3.10. 
Is there a way to create factories for plugin tables?  Thank you :)

**Comment by pabloelcolombiano** [comment]
I cannot reproduce this on my side. Is `Tags` the namespace of your Plugin? This is covered by tests, so at most, you could intend reproducing your issue with a test on the next branch.

But anyway, baking factories should not block you, it is a helper, but do not burn too much time with an issue that might be trivial, but right now not obvious.

If your model is named TagsTable, then your factory should be named TagFactory. If your model is named TagsTagsTable, then your factory should be named TagsTagFactory. Under the namespace Tag\Test\Factory. Factories fetch their info from their table object. So the name of your model is important here, not the name of your table.

Let me know if you are still blocked, providing the fully qualified names of the model and factory classes you have.

Note that the example you provided can also be written as follows:
```php
$tag = TagFactory::make([
            'slug' => 'death_star',
            'label' => 'Death Star'
        ])->persist();
$lesson = LessonFactory::make([
            'label' => 'How to destroy the Death Star'
       ])->with('Tags', [
            'slug' => 'death_star',
            'label' => 'Death Star'
        ])->persist();
```

**Comment by gringlas** [comment]
I'm using tags from a vendor plugin: https://github.com/dereuromark/cakephp-tags. The association to Tags get set in the plugins behavior `$this->addBehavior('Tags.Tag', ['taggedCounter' => false]);`. 
When I bake Factory with the p Flag it seems to me that it assumes to have a plugin, which lives in `plugins` folder, rather like with said Tags plugin in `vendor/dereuromark/cakephp-tags`. 
And for a controller test of mine I would need to query some data with tags, which right now I can't figure out a way to produce this data. I could of course write standard fixtures for that, but the table setup is a bit more complex and I like you plugin for its good readability.

**Comment by pabloelcolombiano** [comment]
How about adding the TagFatory directly to the vendor?

**Comment by gringlas** [comment]
If I do that and try: 
```
$tag = \Tags\Test\Factory\TagFactory::make([
        'slug' => 'death_star',
        'label' => 'Death Star'
])->persist();
```
i will get a `CakephpFixtureFactories\Error\FixtureScenarioException : Class 'Tags\Test\Factory\TagFactory' not found` from `vendor/vierge-noire/cakephp-fixture-factories/src/Scenario/ScenarioAwareTrait.php:51`

**Comment by pabloelcolombiano** [comment]
What might work, is to create a plugin Tags in your app, and place this in your composer.json:

```
"autoload-dev": {
   "psr-4": {
	"Tags\\Test\\": "plugins/Tags/tests/",
   }
},
```

and in this Tags plugin, you can create your factories under plugins/Tags/tests/Factory.

Tell me how did this go!

**Comment by gringlas** [comment]
That works ❤️ 
But in my case I didn't create a plugin, as it already exists and just put the path to the plugin in my autoload-dev, like:
```
"autoload-dev": {
       "psr-4": {
            "App\\Test\\": "tests",
            "Cake\\Test\\": "./vendor/cakephp/cakephp/tests",
            "Tags\\Test\\": "./vendor/dereuromark/cakephp-tags/tests"
        }
}
```
After that I did a `composer dump-autoload` and finally my tests had access to Tags\Test namespace. 
I think this is not an optimal solution, because I have to create code into vendor folder, so that I might rebake the fixture_factory after I updated my dependencies, but I think that is much of a tradeoff here. 

Maybe this should be added to the docs?

**Comment by pabloelcolombiano** [comment]
As you wrote, this is not an optimal solution, for the reasons you gave.

How about:
Writing your TagFactory in your tests/Factory directory, under the App\Test\Factory namespace.

And create your lesson as follows:
```php
$lesson = LessonFactory::make([
   'label' => 'How to destroy the Death Star'
])->with('Tags', \App\Test\Factory\TagFactory::make([
   'slug' => 'death_star',
   'label' => 'Death Star'
]))->persist();
```

Eventually you can wrap all that in a method of the LessonFactory, or even write a trait for all your tagged factories.

**Comment by pabloelcolombiano** [comment]
This is somewhat illustrated in this [test](https://github.com/vierge-noire/cakephp-fixture-factories/blob/next/tests/TestCase/Factory/BaseFactoryAssociationsTest.php#L750).

**Comment by gringlas** [comment]
Yes that is even better, because you won't have to modify composer.json and don't write data into the vendor folder.
As I mentioned earlier I tried to bake a TagFactory with bin/cake bake fixtureFactory Tags and didn't get that to work, because I haven't modified the return value of getRootTableRegistryName. It will be "Tags", but it simply needed to get changed to "TagsTags" and then it is working :) My bad, that I didn't tested that exact case in the first place.

Thanks a lot for your support!
