### ISSUE TITLE
Skip cake entity setter when set fields data

### ISSUE THREAD

**Issue by Erwane** [vierge-noire/cakephp-fixture-factories#165]
When setting data (with `make()`, `setField()` or `patchData()`), if the entity have a `_setField()` method, the data is altered.
It will be nice to add an option to skip this setters.

There is two ways to deactivate usage of setters : 
* In `__construct()` https://api.cakephp.org/4.4/class-Cake.ORM.Entity.html#__construct() with the `useSetters` option.
* In `set()` https://api.cakephp.org/4.4/class-Cake.ORM.Entity.html#set() with `setter` option.

**Comment by pabloelcolombiano** [comment]
Thanks @Erwane for the interesting proposal. I suppose that this could be useful for costly setters, such as hashing of passwords.

The approach I propose is:
* define a protected `$skippedSetters` property in the factories, enabling to disable per default the setters for an array of fields
* this property may be set via a public `skipSettersFor()`method

**Comment by pabloelcolombiano** [comment]
@Erwane here is a [PR](https://github.com/vierge-noire/cakephp-fixture-factories/pull/166) you might want to have a look at.

**Comment by Erwane** [comment]
Very nice. I just added a comment on `DataCompiler::setSkippedSetters`

**Comment by pabloelcolombiano** [comment]
I cannot see your comment @Erwane ?

**Comment by Erwane** [comment]
https://github.com/vierge-noire/cakephp-fixture-factories/pull/166#issuecomment-1171280277
