### ISSUE TITLE
How to specify database connection other than `test`?

### ISSUE THREAD

**Issue by ishan-eventrac** [vierge-noire/cakephp-fixture-factories#174]
In [fixture classes](https://book.cakephp.org/3/en/development/testing.html#creating-fixtures) there a way to set database connection name(via `$connection`) in order to insert data into that database.

How can we achieve same with fixture factories?

**Comment by pabloelcolombiano** [comment]
@ishan-eventrac generally the test data will be inserted in the test DB as documented [here](https://book.cakephp.org/4/en/development/testing.html#test-database-setup). 

You should be able to set the connection of your factory in the `initialize` method as follows:
```php
    protected function initialize(): void
    {
        $this->getTable()->setConnection(ConnectionManager::get('test_foo'));
    }
```
