### ISSUE TITLE
phpdoc @param types of `FactoryAwareTrait::getFactory()` is too narrower than acceptable types

### ISSUE THREAD

**Issue by ckbx-cakebox** [vierge-noire/cakephp-fixture-factories#218]
The second and trailing arguments of `FactoryAwareTrait::getFactory()` can internally accept as same types as the `BaseFactory::make()`, but currently declared as a sequence of `array[]|string` in phpdoc. It cannot accept even the simple associative array, that is one of the main use cases.

**Comment by pabloelcolombiano** [comment]
Thank you for the contribution!
