### ISSUE TITLE
Type of class (e.g abstract) should be detected

### ISSUE THREAD

**Issue by r34117y** [vierge-noire/cakephp-fixture-factories#30]
In my app I have some abstract Table classes.

When I run `bake fixture_factory --all` I get an error because plugin tries to instantiate those classes.

It would be nice if it could detect and exclude those classes.

How to reproduce this error:
- create abstract Table class in /src/ModelTable directory
- run `bin/cake bake fixture_factory --all`

**Comment by pabloelcolombiano** [comment]
@r34117y Thank you for the hint!

I have applied a fix to ignore traits, abstract and interface tables. It is available on the `next` and `cake3_next` branches. Would you mind testing that on your side?

**Comment by r34117y** [comment]
@pabloelcolombiano Thank you for rapid action! And sorry for my late response, but I've been on the road :)

I tested cake3_next branch and all factories have been created correctly (with `bake fixture_factory -af`).
