### ISSUE TITLE
Need a way to NOT generate the Identity Key

### ISSUE THREAD

**Issue by JacobAGTyler** [vierge-noire/cakephp-fixture-factories#31]
The database has a sequence to generate the identities and will enable values to be set by the sequence. I am getting substantial instability through the fixture factories generating a primary key.

In previous vanilla fixtures I simply omitted the IDs in the data array and allowed the Postgres DB to generate the primary key. While there is a mechanism to make primary keys in the data, the function of it is unstable.

```sql
PDOException : SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "user_states_id_seq" does not exist
LINE 1: SELECT setval('user_states_id_seq', 1335968403);
```

I tried using the instance config trait to introduce a BaseFactory config parameter, which could then be used to bypass the line below in the DataCompiler, however there is a second fresh BaseFactory generated, which does not get passed the config parameter and therefore defaults to generating the primary key.

```php
return $this->setPrimaryKey($entity);
```

Could this be a parameter on the persist function?

**Comment by pabloelcolombiano** [comment]
@JacobAGTyler  thanks for your hint!

The tests of the package run in Postgres too, and I am not sure how to exactly replicate your case. If I get you well, you have a `user_states`table in your Postgres database, but the `user_states_id_seq` does not exist, or the user does not have permission to access it?

Something like here?
https://stackoverflow.com/questions/44962937/sequence-does-not-exist-when-it-does-postgres-spring-boot/44963096


If this is not the case, I would need from you that you provide me with the migration file generating the table(s) involved in your case, and a little piece of code generating the error on your side, so I can reproduce it.

**Comment by pabloelcolombiano** [comment]
@JacobAGTyler Any news on that? Can I close the issue?
