### ISSUE TITLE
Add the possibility to attach entities that will always have the same fixed primary key

### ISSUE THREAD

**Issue by pakacuda** [vierge-noire/cakephp-fixture-factories#32]
**Motivation** : 

A test scenario might require the usage of fixtures with fixed primary keys.
For example, one might expect to have one or more entities's association to be associated to the same entities.
With the current implementation, it is difficult to achieve such scenarios with ease and without worrying about primary key collisions.
This feature will allow to associate entities to other ones that will always have the same primary keys.

The behavior of the current API MUST NOT be impacted by the changes in this feature. All current tests MUST NOT be modified and MUST pass.
Additional tests covering the new feature must be added.
The enhancement consists of adding an 'attach' method to the BaseFactory class.
The attach method will support 3 types of parameters.
1. A factory object
2. An entity that has already been persisted
3. An array of entities where each entity has already been persisted

**Comment by pabloelcolombiano** [comment]
Indeed the tests do not run so far on tables with unique fields.

To reproduce the error, we can set for example the field `name` of the CountriesTable to unique:
```
$this->table('countries')
 ->addIndex('name', ['unique' => true])
 ->save();
```

and run in a test:
```
$cities = CityFactory::make(2)->with('Country', ['name' => 'Foo'])->persist();
```

**Comment by pakacuda** [comment]
But this branch will only cover that case for primary keys.
Supporting any column with a unique constraint will probably never be supported. At least, so far, I have no idea how this could be achieved

**Comment by pabloelcolombiano** [comment]
I am thinking of an approach where we provide a $_unique property to the factories. One would e.g. define in the CountryFactory:
```
protected $_unique = [
 'name',
'country_code',
];
```

Knowing this, after persisting, a unique field would instantiate the storing of the produced entity in a registry. When an entity is created, the DataCompiler will know that he has to check if a country with the same name or country_code or id has not been persisted else where. He searches in the registry, and if he finds that this country already exists, he won't mind creating it, but will fetch the existing entity from the repository. It's all in memory, no need to check in the DB.

Per default `id` is unique too of course, so the approach works with Ids.

**Comment by pabloelcolombiano** [comment]
I confirm I think I have a solution by telling the factory which fields should be watched for uniqueness.

We then create a beforeSave Event specific to the Table the factories work on, checking if the entity about to be created already exists.

**Comment by pabloelcolombiano** [comment]
I have a proposal on branch #36_unique_fields, which is summed up in this commit: https://github.com/vierge-noire/cakephp-fixture-factories/commit/6d130f414af5e8996f8f37286dff4137f04f9f73

It is not final, we have to discuss:
- if this is a complete solution to the issue you reported
- about the final behavior of the feature
- code an package documentation need to be documented

**Comment by pabloelcolombiano** [comment]
Any news on your side @pakacuda @vidrascu001 ?

Feel free to submit a PR of your approach, so we can compare the pros and cons of both approaches.

**Comment by pakacuda** [comment]
Yes, we would need to compare the two approches
This week is a very very busy this week !
I'll try to setup a meeting with all of us tomorrow as it should calm down
today

**Comment by pabloelcolombiano** [comment]
Thanks for the update, all the best for this busy week!

**Comment by vidrascu001** [comment]
After our call on 22.01.2020, we decided to extend the with() method and solve the https://github.com/vierge-noire/cakephp-fixture-factories/issues/43 issue instead.
