### ISSUE TITLE
Allow Entities and Array of Entities

### ISSUE THREAD

**Issue by pabloelcolombiano** [vierge-noire/cakephp-fixture-factories#43]
For the moment, the make method allows only arrays, callable, and int.

This should be extended to entity interfaces and arrays of entity interfaces.

Important is that when performing a `->toArray()` on an entity, hidden fields are not "rendered" in the array.

So performing a `->toArray()` will not do, unless we call `->setHidden([])` prior to the `->toArray()`. 

If you take a look at the `Article.php` file, there is extra a hidden array to test that this case is covered. This should be covered by the tests and the implementation.

I propose to create a new `TestCase\Factory\BaseFactoryMakeWithEntity.php` or so class with the tests covering this new feature.

**Comment by pabloelcolombiano** [comment]
Thinking about it again:

For the moment, the Factory works with arrays of data, and I mentioned above calling `->toArray()` on the entities passed in order to work as usual with arrays.

But it might be more interesting to work with entities, and perform a `$this->getTable()->newEntity($makeParameter)`or `$this->getTable()->newEntities($makeParameter)` on the array passed as parameter, to have the factories working per se with entities. I think we can take more out of CakePHP from that, and overcome to issue `->toArray()`brings with hidden fields.

The `BaseFactory::getEntity()`resp. `BaseFactory::getEntities()` become then obsolete, we keep them, but they do even less. 

The DataCompiler::compileEntity returns a real Entity, or array of Entities, and not an array anymore.

If we achieve that, I pay my beer.

**Comment by pabloelcolombiano** [comment]
The package now works with entities, and not with arrays (https://github.com/vierge-noire/cakephp-fixture-factories/issues/54)

This is pushed on dev.

What is left is to allow the dev to feed the Factories with entities and arrays of entities.

**Comment by pabloelcolombiano** [comment]
Note that the `->with()` method also should be feedable with Entities.

**Comment by vidrascu001** [comment]
We are supporting now Entities and Array of Entities

**Comment by pabloelcolombiano** [comment]
Thanks for the contribution.

* The solution you propose lacks the feeding of the `->with()`method with entities as well. This is the most important part of the feature.

* Since the developer is feeding the factory with an entity and the DataCompiler now works internally with entities, we can instead of performing a `->toArray()` on that entity as you did in the `compileEntity` method, directly make use of that entity and let the DataCompiler build over that entity.

You can have a look at the commit above, and let me know if this fits from your point of view.

**Comment by pakacuda** [comment]
Ok, can we merge Pablo’s branch (https://github.com/vierge-noire/cakephp-fixture-factories/tree/%2343_allow_entities_and_array_of_entities) in the next version and move on ?
@pabloelcolombiano : can I create the pull request and merge it as it is ?
AFAIK, Pablo’s commits were done on top of the next branch (cakephp 4) and we also have to port that the cake3_next one, correct ?

**Comment by vidrascu001** [comment]
Yes, true. We also have to port the implementation to the cake3_next branch.

**Comment by pabloelcolombiano** [comment]
@pakacuda I have released a cake3 compatible implementation (simple cherry-pick). I'll merge both cake4 and cake3 implementations in the next- branches in a minute.

**Comment by pabloelcolombiano** [comment]
This is done, I close the issue for now.

Thanks for constructive work together. This is a really nice feature, probably the last before the v2.2 release.
