### ISSUE TITLE
Field names must be quoted or users must pay attentions to it during use persist function?

### ISSUE THREAD

**Issue by k2rn** [vierge-noire/cakephp-fixture-factories#77]
Tables having field names that using keyword like 'key' could not be persisted.
Error Message: `Message: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key, value) VALUES ...`

To avoid this quote field name in `setDefaultTemplate` function like below.

```
    protected function setDefaultTemplate(): void
    {
        $this->setDefaultData(function (Generator $faker) {
            return [
                '`key`' => $faker->word(),
                '`value`' => $faker->randomNumber(),
            ];
        });
    }
```

The message was throwed at `vendor/vierge-noire/cakephp-fixture-factories/src/Factory/BaseFactory.php:334`

The persist method must quote as long as it is not virtual field.
But it seems responsibility of CakePHP itself?

I know it's our code's fault, but sometime we must maintain kind of this type project...
I would appreciate if it was fixed, but we can avoid like above so just let me register issue.

**Comment by pabloelcolombiano** [comment]
@k2rn can't you quote the identifier as described here?
https://book.cakephp.org/4/en/orm/database-basics.html#identifier-quoting

**Comment by k2rn** [comment]
@pabloelcolombiano Oh, I got it, described about this on document already, thank you.
