### ISSUE TITLE
Persist with multiple linked entities

### ISSUE THREAD

**Issue by Drfloo** [vierge-noire/cakephp-fixture-factories#84]
Hi there :)

I was writing some tests and one of them wasn't working.

I found it was due to how i was making my factory. I thought that i was able to chaine 'with' method like this : 

`OrderFactory::make(2)->with('OrdersProducts[5].Products', ['done' => true])->with('ShippingServices')->persist();`

But no. It will make 4 Orders : 2 with Products and 2 with ShippingServices.

So i search in the doc how to do this, but i didn't find a exemple that suit me.

Do you have a nice way to do this ?

Thanks a lot :)

Have a good day

**Comment by pabloelcolombiano** [comment]
Hi @Drfloo,

chaining associations is definitely supported by the package.

Here is an example aiming at reproducing the scenario you propose: https://github.com/vierge-noire/cakephp-fixture-factories/blob/main/tests/TestCase/Factory/BaseFactoryAssociationsTest.php#L690

Could the issue come from the definition of your associations?

**Comment by Drfloo** [comment]
Hi ! Thanks a lot Juan !

It's weird that it's not working for me.

Here's my relations for OrdersTable : 

```php
$this->hasMany('OrdersProducts');
$this->belongsToMany('Products');
$this->belongsTo('ShippingServices', [
'foreignKey' => 'shipping_service_id',
]);
```

**Comment by pabloelcolombiano** [comment]
I am a bit clueless. I have added a second test here, that reproduces even more closely your relations set:
https://github.com/vierge-noire/cakephp-fixture-factories/blob/next/tests/TestCase/Factory/BaseFactoryAssociationsTest.php#L714

Generally in your case I would get rid of the `OrdersProducts` association, as it is trivial, and use only the `Products` association. That might help...

**Comment by Drfloo** [comment]
Ok i will try that.

I added the OrdersProducts relationship because i had problems with created modified when doing : 

```php
 ->with('Products[5]')
```

I'll do some test and come back to you soon.

**Comment by pabloelcolombiano** [comment]
`->with('Products', 5)` works too and is a bit faster to write, imo.

**Comment by pabloelcolombiano** [comment]
Following your pm, if you have issues with date stamp fields, you may add them in the default template of your factories, so they get populated by default.

This is generally not necessary, as illustrated in [this test](https://github.com/vierge-noire/cakephp-fixture-factories/blob/main/tests/TestCase/Factory/EventCollectorTest.php#L118), but I have seen a few setups where this was required.
